/**
 * Sample Strong's lexicon data for Greek and Hebrew word study.
 * Data is public domain (Strong's Concordance, 1890). Expand as needed or load from OpenScriptures/CDN.
 */

import type { StrongsEntry } from "./lexicon-types"

/** Curated sample: common Greek and Hebrew terms. Key = normalized code (G26, H3045). */
export const LEXICON_SAMPLE: Record<string, StrongsEntry> = {
  G26: {
    code: "G26",
    lemma: "ἀγάπη",
    transliteration: "agapē",
    pronunciation: "ag-ah'-pay",
    meaning: "love, goodwill",
    definition: "Love, affection, benevolence; the characteristic attitude of God toward His people and of God’s people toward Him and one another.",
    language: "greek",
  },
  G25: {
    code: "G25",
    lemma: "ἀγαπάω",
    transliteration: "agapaō",
    pronunciation: "ag-ap-ah'-o",
    meaning: "to love",
    definition: "To love (in a social or moral sense); to be fond of, to love dearly.",
    language: "greek",
  },
  G4102: {
    code: "G4102",
    lemma: "πίστις",
    transliteration: "pistis",
    pronunciation: "pis'-tis",
    meaning: "faith, belief, trust",
    definition: "Faith, belief, trust, confidence; fidelity, faithfulness.",
    language: "greek",
  },
  G4100: {
    code: "G4100",
    lemma: "πιστεύω",
    transliteration: "pisteuō",
    pronunciation: "pist-yoo'-o",
    meaning: "to believe, trust",
    definition: "To believe, trust, have confidence in; to entrust. Not merely intellectual assent but commitment and reliance.",
    language: "greek",
  },
  G3056: {
    code: "G3056",
    lemma: "λόγος",
    transliteration: "logos",
    pronunciation: "log'-os",
    meaning: "word, message, statement",
    definition: "Word, speech, message; reason; the divine Word (John 1:1).",
    language: "greek",
  },
  G4982: {
    code: "G4982",
    lemma: "σῴζω",
    transliteration: "sōzō",
    pronunciation: "sode'-zo",
    meaning: "to save, rescue, deliver",
    definition: "To save, rescue, deliver; to preserve from danger or destruction.",
    language: "greek",
  },
  G2962: {
    code: "G2962",
    lemma: "κύριος",
    transliteration: "kyrios",
    pronunciation: "koo'-ree-os",
    meaning: "lord, master, Sir",
    definition: "Lord, master, owner; used of God and of Christ as sovereign.",
    language: "greek",
  },
  H3045: {
    code: "H3045",
    lemma: "יָדַע",
    transliteration: "yādaʿ",
    pronunciation: "yaw-dah'",
    meaning: "to know",
    definition: "To know, perceive, understand; to know relationally (e.g. Adam knew Eve).",
    language: "hebrew",
  },
  H8085: {
    code: "H8085",
    lemma: "שָׁמַע",
    transliteration: "šāmaʿ",
    pronunciation: "shaw-mah'",
    meaning: "to hear, listen, obey",
    definition: "To hear, listen, obey; to give heed. Hebrew hearing implies response.",
    language: "hebrew",
  },
  H3068: {
    code: "H3068",
    lemma: "יְהֹוָה",
    transliteration: "YHWH",
    pronunciation: "yeh-ho-vaw'",
    meaning: "the LORD (proper name of God)",
    definition: "The covenant name of God, often rendered LORD in English Bibles.",
    language: "hebrew",
  },
  H1697: {
    code: "H1697",
    lemma: "דָּבָר",
    transliteration: "dābār",
    pronunciation: "daw-baw'",
    meaning: "word, thing, matter",
    definition: "Word, speech, matter, thing; often used of God’s word or command.",
    language: "hebrew",
  },
  H7451: {
    code: "H7451",
    lemma: "רַע",
    transliteration: "raʿ",
    pronunciation: "rah",
    meaning: "evil, bad, adversity",
    definition: "Evil, bad, adversity; moral evil or calamity.",
    language: "hebrew",
  },
  H7725: {
    code: "H7725",
    lemma: "שׁוּב",
    transliteration: "šûḇ",
    pronunciation: "shoob",
    meaning: "to return, turn back, repent",
    definition: "To return, turn back; to repent; to restore.",
    language: "hebrew",
  },
}
